plugins {
    id 'net.fabricmc.fabric-loom-remap' version "${loom_version}"
    id 'com.diffplug.spotless' version "${spotless_version}"
}

group = project.maven_group
version = project.mod_version

base {
    archivesName = project.archives_base_name
}

repositories {
    maven {
        name = 'Xander Maven'
        url = 'https://maven.isxander.dev/releases'
    }
    maven {
        name = 'Terraformers'
        url = 'https://maven.terraformersmc.com/releases'
    }

    exclusiveContent {
        forRepository {
            maven {
                name = 'Modrinth'
                url = 'https://api.modrinth.com/maven'
            }
        }
        filter {
            includeGroup 'maven.modrinth'
        }
    }
}

loom {
    splitEnvironmentSourceSets()

    mods {
        notenoughhints {
            sourceSet sourceSets.main
            sourceSet sourceSets.client
        }
    }
}

dependencies {
    minecraft "com.mojang:minecraft:${project.minecraft_version}"
    mappings loom.officialMojangMappings()
    modImplementation "net.fabricmc:fabric-loader:${project.loader_version}"
    modImplementation "net.fabricmc.fabric-api:fabric-api:${project.fabric_api_version}"
    modImplementation "dev.isxander:yet-another-config-lib:${project.yacl_version}"
    modCompileOnly "com.terraformersmc:modmenu:${project.modmenu_version}"

    modCompileOnly "maven.modrinth:rlloIFEV:${project.travelers_backpack_version}"

    testImplementation "net.fabricmc:fabric-loader-junit:${project.loader_version}"
}

processResources {
    inputs.property 'version', project.version

    filesMatching('fabric.mod.json') {
        expand version: inputs.properties.version
    }
}

tasks.withType(JavaCompile).configureEach {
    options.release = 21
    options.encoding = 'UTF-8'
    options.compilerArgs.addAll(['-Xlint:all', '-Xlint:-classfile', '-Werror'])
}

test {
    useJUnitPlatform()
}

java {
    withSourcesJar()
    sourceCompatibility = JavaVersion.VERSION_21
    targetCompatibility = JavaVersion.VERSION_21
}

spotless {
    java {
        target 'src/**/*.java'
        leadingTabsToSpaces(4)
        removeUnusedImports()
        trimTrailingWhitespace()
        endWithNewline()
    }

    format 'misc', {
        target '*.gradle', '*.properties', '.gitignore', '.gitattributes', 'src/**/*.json', '.github/**/*.yml', '.github/**/*.yaml'
        trimTrailingWhitespace()
        endWithNewline()
    }
}
